version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: Books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  blazorwebapp:
    build:
      context: ./BlazorWebApp
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__BooksConnection: Host=db;Port=5432;Database=Books;Username=postgres;Password=admin1;IncludeErrorDetail=true
    ports:
      - "8080:8080"

volumes:
  pgdata: