<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookTracker.Common\BookTracker.Common.csproj" />
    <ProjectReference Include="..\BookTracker.DAL\BookTracker.DAL.csproj" />
  </ItemGroup>

</Project>
