 using System;                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                   
  namespace BookTracker.BLL.Models                                                                                                                                                                                                                                                                                 
  {                                                                                                                                                                                                                                                                                                                
      /// <summary>                                                                                                                                                                                                                                                                                                
      /// Represents a basic Author domain model, decoupled from DAL entities.                                                                                                                                                                                                                                     
      /// </summary>                                                                                                                                                                                                                                                                                               
      public class AuthorModel                                                                                                                                                                                                                                                                                     
      {                                                                                                                                                                                                                                                                                                            
          /// <summary>Gets or sets the unique identifier for the author.</summary>                                                                                                                                                                                                                                
          public Guid AuthorPk { get; set; }                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                   
          /// <summary>The name of the author.</summary>                                                                                                                                                                                                                                                           
          public string Name { get; set; } = string.Empty;                                                                                                                                                                                                                                                         
      }                                                                                                                                                                                                                                                                                                            
  }