using System;                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                   
  namespace BookTracker.BLL.Models                                                                                                                                                                                                                                                                                 
  {                                                                                                                                                                                                                                                                                                                
      /// <summary>                                                                                                                                                                                                                                                                                                
      /// Represents a basic Genre domain model, decoupled from DAL entities.                                                                                                                                                                                                                                      
      /// </summary>                                                                                                                                                                                                                                                                                               
      public class GenreModel                                                                                                                                                                                                                                                                                      
      {                                                                                                                                                                                                                                                                                                            
          /// <summary>Gets or sets the unique identifier for the genre.</summary>                                                                                                                                                                                                                                 
          public Guid GenrePk { get; set; }                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                   
          /// <summary>The name of the genre (e.g., "Science Fiction").</summary>                                                                                                                                                                                                                                  
          public string Name { get; set; } = string.Empty;                                                                                                                                                                                                                                                         
      }                                                                                                                                                                                                                                                                                                            
  }      