// <auto-generated />
using System;
using BookTracker.DAL.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookTracker.DAL.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20260216103115_AddTranslationTables")]
    partial class AddTranslationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookTracker.DAL.Entities.Authors.Author", b =>
                {
                    b.Property<Guid>("AuthorPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuthorPk");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Books.Book", b =>
                {
                    b.Property<Guid>("BookPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorPk")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateRead")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("GenrePk")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookPk");

                    b.HasIndex("AuthorPk");

                    b.HasIndex("GenrePk");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Genres.Genre", b =>
                {
                    b.Property<Guid>("GenrePk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenrePk");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Languages.Language", b =>
                {
                    b.Property<byte>("LanguagePk")
                        .HasColumnType("smallint");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LanguagePk");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Translations.AuthorTranslation", b =>
                {
                    b.Property<int>("AuthorTranslationPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuthorTranslationPk"));

                    b.Property<Guid>("AuthorPk")
                        .HasColumnType("uuid");

                    b.Property<byte>("LanguagePk")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuthorTranslationPk");

                    b.HasIndex("LanguagePk");

                    b.HasIndex("AuthorPk", "LanguagePk")
                        .IsUnique();

                    b.ToTable("AuthorTranslations");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Translations.BookTranslation", b =>
                {
                    b.Property<int>("BookTranslationPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookTranslationPk"));

                    b.Property<Guid>("BookPk")
                        .HasColumnType("uuid");

                    b.Property<byte>("LanguagePk")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookTranslationPk");

                    b.HasIndex("LanguagePk");

                    b.HasIndex("BookPk", "LanguagePk")
                        .IsUnique();

                    b.ToTable("BookTranslations");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Translations.GenreTranslation", b =>
                {
                    b.Property<int>("GenreTranslationPk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreTranslationPk"));

                    b.Property<Guid>("GenrePk")
                        .HasColumnType("uuid");

                    b.Property<byte>("LanguagePk")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreTranslationPk");

                    b.HasIndex("LanguagePk");

                    b.HasIndex("GenrePk", "LanguagePk")
                        .IsUnique();

                    b.ToTable("GenreTranslations");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Books.Book", b =>
                {
                    b.HasOne("BookTracker.DAL.Entities.Authors.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorPk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookTracker.DAL.Entities.Genres.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenrePk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Translations.AuthorTranslation", b =>
                {
                    b.HasOne("BookTracker.DAL.Entities.Authors.Author", "Author")
                        .WithMany("Translations")
                        .HasForeignKey("AuthorPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookTracker.DAL.Entities.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguagePk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Translations.BookTranslation", b =>
                {
                    b.HasOne("BookTracker.DAL.Entities.Books.Book", "Book")
                        .WithMany("Translations")
                        .HasForeignKey("BookPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookTracker.DAL.Entities.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguagePk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Translations.GenreTranslation", b =>
                {
                    b.HasOne("BookTracker.DAL.Entities.Genres.Genre", "Genre")
                        .WithMany("Translations")
                        .HasForeignKey("GenrePk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookTracker.DAL.Entities.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguagePk")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Authors.Author", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Books.Book", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("BookTracker.DAL.Entities.Genres.Genre", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
